# Generated by Django 4.2.7 on 2025-10-28 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='模板名称')),
                ('category', models.CharField(choices=[('interface', '接口配置'), ('routing', '路由配置'), ('acl', '访问控制列表'), ('vlan', 'VLAN 配置'), ('qos', 'QoS 配置'), ('security', '安全配置'), ('system', '系统配置'), ('other', '其他')], default='other', max_length=50, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='定义模板中使用的变量及其默认值', verbose_name='变量定义')),
                ('example_vars', models.JSONField(blank=True, default=dict, help_text='用于预览的示例变量值', verbose_name='示例变量')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔的标签', max_length=200, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '配置模板',
                'verbose_name_plural': '配置模板',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('variables', models.JSONField(default=dict, verbose_name='变量定义')),
                ('change_note', models.TextField(blank=True, verbose_name='变更说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='templates_mgr.configtemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '模板版本',
                'verbose_name_plural': '模板版本',
                'ordering': ['-version'],
                'unique_together': {('template', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='变量名')),
                ('variable_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('boolean', '布尔值'), ('list', '列表'), ('dict', '字典')], default='string', max_length=20, verbose_name='类型')),
                ('default_value', models.TextField(blank=True, verbose_name='默认值')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='描述')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_definitions', to='templates_mgr.configtemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '模板变量',
                'verbose_name_plural': '模板变量',
                'ordering': ['order', 'name'],
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='configtemplate',
            index=models.Index(fields=['category'], name='templates_m_categor_f2fa17_idx'),
        ),
        migrations.AddIndex(
            model_name='configtemplate',
            index=models.Index(fields=['is_active'], name='templates_m_is_acti_649b9d_idx'),
        ),
    ]
