# Generated by Django 4.2.7 on 2025-10-28 04:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='凭据名称')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('enable_password', models.CharField(blank=True, max_length=255, verbose_name='Enable 密码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备凭据',
                'verbose_name_plural': '设备凭据',
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='组名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备组',
                'verbose_name_plural': '设备组',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(unique=True, validators=[django.core.validators.validate_ipv4_address], verbose_name='IP 地址')),
                ('device_type', models.CharField(choices=[('router', '路由器'), ('switch', '交换机'), ('firewall', '防火墙'), ('other', '其他')], default='switch', max_length=20, verbose_name='设备类型')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='设备型号')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='序列号')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH 端口')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('enable_password', models.CharField(blank=True, max_length=255, verbose_name='Enable 密码')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='OS 版本')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('maintenance', '维护中'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间')),
                ('last_check_result', models.TextField(blank=True, verbose_name='最后检查结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_devices', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('groups', models.ManyToManyField(blank=True, related_name='devices', to='devices.devicegroup', verbose_name='所属组')),
            ],
            options={
                'verbose_name': '网络设备',
                'verbose_name_plural': '网络设备',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['ip_address'], name='devices_dev_ip_addr_477d04_idx'), models.Index(fields=['hostname'], name='devices_dev_hostnam_7489a0_idx'), models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx')],
            },
        ),
    ]
