# Generated by Django 4.2.7 on 2025-10-28 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_content', models.TextField(verbose_name='配置内容')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('in_progress', '进行中')], default='success', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('backup_type', models.CharField(default='manual', help_text='manual/scheduled/auto', max_length=50, verbose_name='备份类型')),
                ('description', models.TextField(blank=True, verbose_name='备份说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='devices.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '配置备份',
                'verbose_name_plural': '配置备份',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('in_progress', '进行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('output', models.TextField(blank=True, verbose_name='输出')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_history', to='backups.configbackup', verbose_name='备份')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_restores', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_history', to='devices.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '恢复历史',
                'verbose_name_plural': '恢复历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_content', models.TextField(verbose_name='差异内容')),
                ('lines_added', models.IntegerField(default=0, verbose_name='新增行数')),
                ('lines_removed', models.IntegerField(default=0, verbose_name='删除行数')),
                ('lines_changed', models.IntegerField(default=0, verbose_name='修改行数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('backup_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_as_new', to='backups.configbackup', verbose_name='新备份')),
                ('backup_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_as_old', to='backups.configbackup', verbose_name='旧备份')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '配置差异',
                'verbose_name_plural': '配置差异',
                'ordering': ['-created_at'],
                'unique_together': {('backup_old', 'backup_new')},
            },
        ),
        migrations.AddIndex(
            model_name='configbackup',
            index=models.Index(fields=['device', '-created_at'], name='backups_con_device__d50c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='configbackup',
            index=models.Index(fields=['status'], name='backups_con_status_c06078_idx'),
        ),
    ]
