# Generated by Django 4.2.7 on 2025-10-28 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('active_users', models.IntegerField(default=0, verbose_name='活跃用户数')),
                ('new_users', models.IntegerField(default=0, verbose_name='新增用户数')),
                ('login_success', models.IntegerField(default=0, verbose_name='登录成功次数')),
                ('login_failed', models.IntegerField(default=0, verbose_name='登录失败次数')),
                ('total_operations', models.IntegerField(default=0, verbose_name='总操作次数')),
                ('create_operations', models.IntegerField(default=0, verbose_name='创建操作')),
                ('update_operations', models.IntegerField(default=0, verbose_name='更新操作')),
                ('delete_operations', models.IntegerField(default=0, verbose_name='删除操作')),
                ('execute_operations', models.IntegerField(default=0, verbose_name='执行操作')),
                ('tasks_created', models.IntegerField(default=0, verbose_name='创建任务数')),
                ('tasks_success', models.IntegerField(default=0, verbose_name='成功任务数')),
                ('tasks_failed', models.IntegerField(default=0, verbose_name='失败任务数')),
                ('backups_created', models.IntegerField(default=0, verbose_name='创建备份数')),
                ('backups_success', models.IntegerField(default=0, verbose_name='成功备份数')),
                ('backups_failed', models.IntegerField(default=0, verbose_name='失败备份数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '操作统计',
                'verbose_name_plural': '操作统计',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录历史',
                'verbose_name_plural': '登录历史',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_login_user_id_9e67e8_idx'), models.Index(fields=['status', '-created_at'], name='audit_login_status_9282ff_idx'), models.Index(fields=['-created_at'], name='audit_login_created_12040e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('view', '查看'), ('execute', '执行'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('import', '导入'), ('backup', '备份'), ('restore', '恢复'), ('other', '其他')], max_length=20, verbose_name='操作类型')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='info', max_length=20, verbose_name='级别')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='对象表示')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='变更详情')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['level', '-created_at'], name='audit_audit_level_788d83_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx')],
            },
        ),
    ]
