# Generated by Django 4.2.7 on 2025-10-28 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates_mgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('command', '命令执行'), ('template', '模板下发'), ('backup', '配置备份'), ('health_check', '健康检查')], max_length=20, verbose_name='任务类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('template_vars', models.JSONField(blank=True, default=dict, verbose_name='模板变量')),
                ('commands', models.TextField(blank=True, help_text='每行一个命令', verbose_name='命令列表')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('partial', '部分成功'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, help_text='百分比 0-100', verbose_name='进度')),
                ('celery_task_id', models.CharField(blank=True, max_length=100, verbose_name='Celery 任务 ID')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('total_count', models.IntegerField(default=0, verbose_name='总数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('target_devices', models.ManyToManyField(blank=True, related_name='tasks', to='devices.device', verbose_name='目标设备')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='tasks', to='devices.devicegroup', verbose_name='目标设备组')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_mgr.configtemplate', verbose_name='配置模板')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('task_type', models.CharField(choices=[('command', '命令执行'), ('template', '模板下发'), ('backup', '配置备份'), ('health_check', '健康检查')], max_length=20, verbose_name='任务类型')),
                ('template_vars', models.JSONField(blank=True, default=dict, verbose_name='模板变量')),
                ('commands', models.TextField(blank=True, verbose_name='命令列表')),
                ('frequency', models.CharField(choices=[('once', '一次性'), ('hourly', '每小时'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], max_length=20, verbose_name='频率')),
                ('cron_expression', models.CharField(blank=True, help_text='自定义 Cron 表达式', max_length=100, verbose_name='Cron 表达式')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('target_devices', models.ManyToManyField(blank=True, related_name='schedules', to='devices.device', verbose_name='目标设备')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='schedules', to='devices.devicegroup', verbose_name='目标设备组')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_mgr.configtemplate', verbose_name='配置模板')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('output', models.TextField(blank=True, verbose_name='输出')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='devices.device', verbose_name='设备')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务结果',
                'verbose_name_plural': '任务结果',
                'ordering': ['device__name'],
                'indexes': [models.Index(fields=['task', 'status'], name='tasks_taskr_task_id_c73d59_idx'), models.Index(fields=['device', 'created_at'], name='tasks_taskr_device__313b74_idx')],
                'unique_together': {('task', 'device')},
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='tasks_task_task_ty_45f0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='tasks_task_created_be1ba2_idx'),
        ),
    ]
